import { DiagnosticItem, TestPriceComparisonGroup } from '../types';

export const initialCTScans: DiagnosticItem[] = [
  {
    id: 'ct-1',
    name: 'CT Head / Brain (Plain & High-Resolution)',
    type: 'ct_scan',
    centerName: 'Bhagyodaya Tirth Diagnostic Centre',
    centerAddress: 'Khurai Road, Sagar',
    locality: 'Khurai Road',
    ratingAverage: 4.95,
    reviewsCount: 142,
    preparation: 'No Fasting Required',
    reportTurnaround: 'Film & Report in 2 Hours',
    mrp: 2400,
    price: 1399,
    discountPercentage: 42,
    phone: '07582-472000',
    badge: '128-Slice Low Dose',
    bodyPart: 'Brain & Cranium',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'ct-2',
    name: 'HRCT Chest (High Resolution Lung CT)',
    type: 'ct_scan',
    centerName: 'Bansal Advanced Imaging & Scan',
    centerAddress: 'Civil Lines, Sagar',
    locality: 'Civil Lines',
    ratingAverage: 4.92,
    reviewsCount: 218,
    preparation: 'Light Breakfast Allowed',
    reportTurnaround: 'Digital Report in 3 Hours',
    mrp: 4500,
    price: 2499,
    discountPercentage: 44,
    phone: '07582-401122',
    badge: 'Dual Source Ultra-Fast',
    bodyPart: 'Lungs & Thorax',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'ct-3',
    name: 'CT Whole Abdomen & Pelvis (CECT)',
    type: 'ct_scan',
    centerName: 'Sagar City Scan & MRI Centre',
    centerAddress: 'Deendayal Nagar, Sagar',
    locality: 'Deendayal Nagar',
    ratingAverage: 4.88,
    reviewsCount: 96,
    preparation: '4-6 Hours Fasting + Oral Contrast',
    reportTurnaround: 'Same Day by 5 PM',
    mrp: 5500,
    price: 3299,
    discountPercentage: 40,
    phone: '07582-243388',
    badge: 'Contrast Enhanced CECT',
    bodyPart: 'Abdomen & Pelvis',
    imageUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'ct-4',
    name: 'CT PNS (Paranasal Sinuses Coronal & Axial)',
    type: 'ct_scan',
    centerName: 'BMC Government Medical Imaging',
    centerAddress: 'Medical College Campus, Sagar',
    locality: 'Medical College',
    ratingAverage: 4.85,
    reviewsCount: 175,
    preparation: 'No Fasting Required',
    reportTurnaround: 'Film in 1.5 Hours',
    mrp: 2000,
    price: 1150,
    discountPercentage: 42,
    phone: '07582-234500',
    badge: '3D Sinus Mapping',
    bodyPart: 'Nose & Sinuses',
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'ct-5',
    name: 'CT Lumbar / Cervical Spine (3D Reconstruction)',
    type: 'ct_scan',
    centerName: 'Bhagyodaya Tirth Diagnostic Centre',
    centerAddress: 'Khurai Road, Sagar',
    locality: 'Khurai Road',
    ratingAverage: 4.94,
    reviewsCount: 110,
    preparation: 'No Fasting Required',
    reportTurnaround: 'Film & CD in 2 Hours',
    mrp: 3200,
    price: 1850,
    discountPercentage: 42,
    phone: '07582-472000',
    badge: 'Sub-Millimeter Thin Cut',
    bodyPart: 'Spine & Vertebrae',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'ct-6',
    name: 'CT KUB (Kidney, Ureter & Urinary Bladder)',
    type: 'ct_scan',
    centerName: 'Bansal Advanced Imaging & Scan',
    centerAddress: 'Civil Lines, Sagar',
    locality: 'Civil Lines',
    ratingAverage: 4.91,
    reviewsCount: 134,
    preparation: 'Hydration & Full Bladder',
    reportTurnaround: 'Digital Report in 2 Hours',
    mrp: 3000,
    price: 1750,
    discountPercentage: 41,
    phone: '07582-401122',
    badge: 'Stone Protocol Non-Contrast',
    bodyPart: 'Renal & Bladder',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'ct-7',
    name: 'CT Coronary Angiography (Heart Vessels)',
    type: 'ct_scan',
    centerName: 'Sagar Heart & Diagnostic Institute',
    centerAddress: 'Tilli Road, Sagar',
    locality: 'Tilli Road',
    ratingAverage: 4.97,
    reviewsCount: 88,
    preparation: '4 Hours Fasting & Heart Rate Control',
    reportTurnaround: 'Report with 3D Video',
    mrp: 11000,
    price: 6499,
    discountPercentage: 41,
    phone: '07582-268800',
    badge: 'Non-Invasive Cardiac 256-Slice',
    bodyPart: 'Coronary Arteries',
    imageUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'ct-8',
    name: 'CT Neck Soft Tissue & Thyroid',
    type: 'ct_scan',
    centerName: 'Bhagyodaya Tirth Diagnostic Centre',
    centerAddress: 'Khurai Road, Sagar',
    locality: 'Khurai Road',
    ratingAverage: 4.89,
    reviewsCount: 62,
    preparation: 'Light Fasting 2 Hours',
    reportTurnaround: 'Film in 2 Hours',
    mrp: 3500,
    price: 1999,
    discountPercentage: 43,
    phone: '07582-472000',
    badge: 'Contrast Enhanced',
    bodyPart: 'Neck & Larynx',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=500&auto=format&fit=crop&q=80',
  },
];

export const initialPathologyTests: DiagnosticItem[] = [
  {
    id: 'path-1',
    name: 'Complete Blood Count (CBC) with ESR (28 Parameters)',
    type: 'pathology',
    centerName: 'Apollo Diagnostics Sagar',
    centerAddress: 'Civil Lines, Sagar',
    locality: 'Civil Lines',
    ratingAverage: 4.96,
    reviewsCount: 340,
    preparation: 'No Fasting Required',
    reportTurnaround: 'Report in 3 Hours (Digital)',
    mrp: 450,
    price: 199,
    discountPercentage: 55,
    phone: '07582-249911',
    badge: 'NABL Certified 6-Part Cell Counter',
    homeCollectionAvailable: true,
    sampleType: 'Blood (EDTA)',
    imageUrl: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'path-2',
    name: 'Lipid Profile Comprehensive (8 Vital Lipids)',
    type: 'pathology',
    centerName: 'Bhagyodaya Tirth Central Laboratory',
    centerAddress: 'Khurai Road, Sagar',
    locality: 'Khurai Road',
    ratingAverage: 4.94,
    reviewsCount: 285,
    preparation: '10-12 Hours Overnight Fasting',
    reportTurnaround: 'Same Day by 2 PM',
    mrp: 850,
    price: 399,
    discountPercentage: 53,
    phone: '07582-472000',
    badge: 'Fully Automated Chemistry',
    homeCollectionAvailable: true,
    sampleType: 'Serum',
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'path-3',
    name: 'HbA1c (Glycated Hemoglobin) Diabetes Panel',
    type: 'pathology',
    centerName: 'SRL Diagnostics Sagar',
    centerAddress: 'Katra Bazar, Sagar',
    locality: 'Katra Bazar',
    ratingAverage: 4.93,
    reviewsCount: 220,
    preparation: 'No Fasting Required',
    reportTurnaround: 'Report in 4 Hours',
    mrp: 650,
    price: 299,
    discountPercentage: 54,
    phone: '07582-241800',
    badge: 'HPLC Gold Standard Method',
    homeCollectionAvailable: true,
    sampleType: 'Whole Blood',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'path-4',
    name: 'Liver Function Test (LFT) with Enzymes & Proteins',
    type: 'pathology',
    centerName: 'Apollo Diagnostics Sagar',
    centerAddress: 'Civil Lines, Sagar',
    locality: 'Civil Lines',
    ratingAverage: 4.91,
    reviewsCount: 195,
    preparation: '8 Hours Fasting Recommended',
    reportTurnaround: 'Report in 4 Hours',
    mrp: 900,
    price: 449,
    discountPercentage: 50,
    phone: '07582-249911',
    badge: '11 Liver Health Parameters',
    homeCollectionAvailable: true,
    sampleType: 'Serum',
    imageUrl: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'path-5',
    name: 'Thyroid Profile Total (T3, T4, Ultra TSH)',
    type: 'pathology',
    centerName: 'Bhagyodaya Tirth Central Laboratory',
    centerAddress: 'Khurai Road, Sagar',
    locality: 'Khurai Road',
    ratingAverage: 4.95,
    reviewsCount: 310,
    preparation: 'Morning Sample (Fasting Preferred)',
    reportTurnaround: 'Same Day by 3 PM',
    mrp: 600,
    price: 299,
    discountPercentage: 50,
    phone: '07582-472000',
    badge: 'Chemiluminescence (CLIA)',
    homeCollectionAvailable: true,
    sampleType: 'Serum',
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'path-6',
    name: 'Vitamin D (25-OH) & Vitamin B12 Duo Pack',
    type: 'pathology',
    centerName: 'Dr. Lal PathLabs Sagar',
    centerAddress: 'Gujarati Bazar, Sagar',
    locality: 'Gujarati Bazar',
    ratingAverage: 4.97,
    reviewsCount: 420,
    preparation: 'No Fasting Required',
    reportTurnaround: 'Digital Report in 12 Hours',
    mrp: 2200,
    price: 899,
    discountPercentage: 59,
    phone: '07582-225600',
    badge: 'Immunity & Bone Energy Duo',
    homeCollectionAvailable: true,
    sampleType: 'Blood Serum',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'path-7',
    name: 'Kidney Function Test (KFT / RFT) with Electrolytes',
    type: 'pathology',
    centerName: 'Apollo Diagnostics Sagar',
    centerAddress: 'Civil Lines, Sagar',
    locality: 'Civil Lines',
    ratingAverage: 4.88,
    reviewsCount: 160,
    preparation: '8 Hours Fasting',
    reportTurnaround: 'Report in 3.5 Hours',
    mrp: 850,
    price: 399,
    discountPercentage: 53,
    phone: '07582-249911',
    badge: 'Creatinine + Urea + Sodium/Potassium',
    homeCollectionAvailable: true,
    sampleType: 'Serum',
    imageUrl: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'path-8',
    name: 'Executive Whole Body Health Checkup (84 Parameters)',
    type: 'pathology',
    centerName: 'Bhagyodaya Tirth Central Laboratory',
    centerAddress: 'Khurai Road, Sagar',
    locality: 'Khurai Road',
    ratingAverage: 4.98,
    reviewsCount: 512,
    preparation: '10 Hours Overnight Fasting',
    reportTurnaround: 'Full Digital Dossier in 24 Hours',
    mrp: 4500,
    price: 1599,
    discountPercentage: 64,
    phone: '07582-472000',
    badge: 'All-in-One Comprehensive Master Panel',
    homeCollectionAvailable: true,
    sampleType: 'Blood & Urine',
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=500&auto=format&fit=crop&q=80',
  },
];

export const initialXRays: DiagnosticItem[] = [
  {
    id: 'xray-1',
    name: 'Digital Chest X-Ray PA View (High-Definition DR)',
    type: 'x_ray',
    centerName: 'Bhagyodaya Tirth Radiology Unit',
    centerAddress: 'Khurai Road, Sagar',
    locality: 'Khurai Road',
    ratingAverage: 4.95,
    reviewsCount: 380,
    preparation: 'Remove Metallic Jewelry & Zippers',
    reportTurnaround: 'Digital Film & Report in 20 Mins',
    mrp: 600,
    price: 299,
    discountPercentage: 50,
    phone: '07582-472000',
    badge: 'Direct Digital Radiography (DR)',
    bodyPart: 'Lungs & Rib Cage',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'xray-2',
    name: 'X-Ray Knee Joint (AP & Lateral Both Views)',
    type: 'x_ray',
    centerName: 'Bansal Imaging Center',
    centerAddress: 'Civil Lines, Sagar',
    locality: 'Civil Lines',
    ratingAverage: 4.92,
    reviewsCount: 190,
    preparation: 'No Preparation Required',
    reportTurnaround: 'Film in 30 Mins',
    mrp: 800,
    price: 399,
    discountPercentage: 50,
    phone: '07582-401122',
    badge: 'Weight Bearing Standing View',
    bodyPart: 'Knees & Joints',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'xray-3',
    name: 'X-Ray Lumbar Spine (AP & Lateral Standing)',
    type: 'x_ray',
    centerName: 'Sagar Advanced X-Ray Clinic',
    centerAddress: 'Deendayal Nagar, Sagar',
    locality: 'Deendayal Nagar',
    ratingAverage: 4.88,
    reviewsCount: 145,
    preparation: 'Overnight Bowel Clearance Preferred',
    reportTurnaround: 'Film in 30 Mins',
    mrp: 900,
    price: 449,
    discountPercentage: 50,
    phone: '07582-243388',
    badge: 'Spinal Alignment & Disc Space',
    bodyPart: 'Lower Back & Spine',
    imageUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'xray-4',
    name: 'X-Ray Cervical Spine (AP, Lateral & Oblique Views)',
    type: 'x_ray',
    centerName: 'Bhagyodaya Tirth Radiology Unit',
    centerAddress: 'Khurai Road, Sagar',
    locality: 'Khurai Road',
    ratingAverage: 4.93,
    reviewsCount: 160,
    preparation: 'Remove Necklaces & Ear Accessories',
    reportTurnaround: 'Immediate Film on App & WhatsApp',
    mrp: 850,
    price: 399,
    discountPercentage: 53,
    phone: '07582-472000',
    badge: 'Neck Pain & Nerve Foramen DR',
    bodyPart: 'Neck & Cervical Spine',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'xray-5',
    name: 'X-Ray PNS (Paranasal Sinuses Water\'s View)',
    type: 'x_ray',
    centerName: 'Bansal Imaging Center',
    centerAddress: 'Civil Lines, Sagar',
    locality: 'Civil Lines',
    ratingAverage: 4.89,
    reviewsCount: 115,
    preparation: 'No Preparation Required',
    reportTurnaround: 'Film in 25 Mins',
    mrp: 650,
    price: 320,
    discountPercentage: 51,
    phone: '07582-401122',
    badge: 'Sinusitis & Polyps DR Film',
    bodyPart: 'Sinuses & Facial Bones',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'xray-6',
    name: 'X-Ray Pelvis with Both Hip Joints (AP View)',
    type: 'x_ray',
    centerName: 'BMC Government Radiodiagnosis',
    centerAddress: 'Medical College Campus, Sagar',
    locality: 'Medical College',
    ratingAverage: 4.86,
    reviewsCount: 130,
    preparation: 'No Fasting Required',
    reportTurnaround: 'Film in 30 Mins',
    mrp: 750,
    price: 349,
    discountPercentage: 53,
    phone: '07582-234500',
    badge: 'High Clarity Digital Film',
    bodyPart: 'Pelvis & Hip Joints',
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'xray-7',
    name: 'X-Ray Abdomen Erect & Supine (KUB / Gas Pattern)',
    type: 'x_ray',
    centerName: 'Bhagyodaya Tirth Radiology Unit',
    centerAddress: 'Khurai Road, Sagar',
    locality: 'Khurai Road',
    ratingAverage: 4.94,
    reviewsCount: 95,
    preparation: '4 Hours Fasting Preferred',
    reportTurnaround: 'Film & Radiologist Report in 25 Mins',
    mrp: 800,
    price: 380,
    discountPercentage: 52,
    phone: '07582-472000',
    badge: 'Obstruction & Calculus DR',
    bodyPart: 'Abdomen & Diaphragm',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'xray-8',
    name: 'X-Ray Foot & Ankle Joint (AP & Oblique Views)',
    type: 'x_ray',
    centerName: 'Sagar Advanced X-Ray Clinic',
    centerAddress: 'Deendayal Nagar, Sagar',
    locality: 'Deendayal Nagar',
    ratingAverage: 4.87,
    reviewsCount: 82,
    preparation: 'No Preparation Required',
    reportTurnaround: 'Film in 20 Mins',
    mrp: 650,
    price: 320,
    discountPercentage: 51,
    phone: '07582-243388',
    badge: 'Fracture & Sprain DR Screening',
    bodyPart: 'Ankle & Foot',
    imageUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=500&auto=format&fit=crop&q=80',
  },
];

export const initialPriceComparisonGroups: TestPriceComparisonGroup[] = [
  {
    testId: 'cmp-ct-1',
    testName: 'HRCT Chest (High Resolution Lung CT)',
    category: 'ct_scan',
    description: 'Gold standard 3D computed tomography scan for lung parenchymal diseases, post-viral fibrosis, and airway infections.',
    centers: [
      {
        centerId: 'c1',
        centerName: 'Bhagyodaya Tirth Diagnostic Centre',
        centerType: 'Super Specialty Hospital',
        locality: 'Khurai Road, Sagar',
        distanceKm: 2.1,
        rating: 4.95,
        accreditation: 'NABH Verified & 128-Slice DR',
        mrp: 4500,
        price: 2199,
        savings: 2301,
        turnaroundTime: '2 Hours Digital Film + CD',
        phone: '07582-472000',
        availableSlot: 'Today, 02:30 PM (No Wait)',
        isLowestPrice: true,
        isFastestReport: true,
      },
      {
        centerId: 'c2',
        centerName: 'Bansal Advanced Imaging & Scan',
        centerType: 'Dedicated Radiology Centre',
        locality: 'Civil Lines, Sagar',
        distanceKm: 3.4,
        rating: 4.91,
        accreditation: 'Dual Source Ultra-Fast Scanner',
        mrp: 4800,
        price: 2499,
        savings: 2301,
        turnaroundTime: '3 Hours Digital Delivery',
        phone: '07582-401122',
        availableSlot: 'Today, 03:15 PM',
        isLowestPrice: false,
        isFastestReport: false,
      },
      {
        centerId: 'c3',
        centerName: 'Sagar City Scan & MRI Centre',
        centerType: 'Multi-Diagnostic Center',
        locality: 'Deendayal Nagar, Sagar',
        distanceKm: 4.8,
        rating: 4.86,
        accreditation: 'AERB Approved 64-Slice',
        mrp: 5000,
        price: 2800,
        savings: 2200,
        turnaroundTime: '4 Hours',
        phone: '07582-243388',
        availableSlot: 'Today, 04:00 PM',
        isLowestPrice: false,
        isFastestReport: false,
      },
    ],
  },
  {
    testId: 'cmp-ct-2',
    testName: 'CT Brain / Head (Plain & High Speed)',
    category: 'ct_scan',
    description: 'Immediate diagnostic imaging for headaches, head injuries, trauma, stroke, and intracranial evaluation.',
    centers: [
      {
        centerId: 'c1',
        centerName: 'Bhagyodaya Tirth Diagnostic Centre',
        centerType: 'Super Specialty Hospital',
        locality: 'Khurai Road, Sagar',
        distanceKm: 2.1,
        rating: 4.96,
        accreditation: '24/7 Emergency Stroke Ready',
        mrp: 2400,
        price: 1399,
        savings: 1001,
        turnaroundTime: '1.5 Hours Instant Film',
        phone: '07582-472000',
        availableSlot: 'Instant Token Available',
        isLowestPrice: false,
        isFastestReport: true,
      },
      {
        centerId: 'c4',
        centerName: 'BMC Government Radiodiagnosis',
        centerType: 'Government Medical College',
        locality: 'Medical College Campus, Sagar',
        distanceKm: 5.2,
        rating: 4.85,
        accreditation: 'State Medical Diagnostic Unit',
        mrp: 2000,
        price: 1100,
        savings: 900,
        turnaroundTime: '3 Hours',
        phone: '07582-234500',
        availableSlot: 'Today, 01:00 PM',
        isLowestPrice: true,
        isFastestReport: false,
      },
      {
        centerId: 'c2',
        centerName: 'Bansal Advanced Imaging & Scan',
        centerType: 'Dedicated Radiology Centre',
        locality: 'Civil Lines, Sagar',
        distanceKm: 3.4,
        rating: 4.92,
        accreditation: 'High Precision Neuro Protocol',
        mrp: 2500,
        price: 1550,
        savings: 950,
        turnaroundTime: '2 Hours',
        phone: '07582-401122',
        availableSlot: 'Today, 02:00 PM',
        isLowestPrice: false,
        isFastestReport: false,
      },
    ],
  },
  {
    testId: 'cmp-path-1',
    testName: 'Complete Blood Count (CBC) with ESR',
    category: 'pathology',
    description: 'Comprehensive 28-parameter hemogram covering Hemoglobin, WBC, Platelets, RBC indices, and inflammation marker.',
    centers: [
      {
        centerId: 'c5',
        centerName: 'Apollo Diagnostics Sagar',
        centerType: 'National NABL Laboratory',
        locality: 'Civil Lines, Sagar',
        distanceKm: 2.8,
        rating: 4.96,
        accreditation: 'NABL Certified 100% Barcoded',
        mrp: 450,
        price: 199,
        savings: 251,
        turnaroundTime: '3 Hours on App',
        phone: '07582-249911',
        availableSlot: 'Home Collection in 15 Mins',
        isLowestPrice: true,
        isFastestReport: true,
      },
      {
        centerId: 'c6',
        centerName: 'Bhagyodaya Central Laboratory',
        centerType: 'Hospital Diagnostic Lab',
        locality: 'Khurai Road, Sagar',
        distanceKm: 2.1,
        rating: 4.94,
        accreditation: '6-Part Differential Sysmex Counter',
        mrp: 400,
        price: 220,
        savings: 180,
        turnaroundTime: '2.5 Hours Walk-In',
        phone: '07582-472000',
        availableSlot: 'Walk-In Anytime (No Fasting)',
        isLowestPrice: false,
        isFastestReport: false,
      },
      {
        centerId: 'c7',
        centerName: 'Dr. Lal PathLabs Sagar',
        centerType: 'National Reference Lab',
        locality: 'Gujarati Bazar, Sagar',
        distanceKm: 3.9,
        rating: 4.95,
        accreditation: 'NABL & CAP Accredited',
        mrp: 500,
        price: 299,
        savings: 201,
        turnaroundTime: '4 Hours',
        phone: '07582-225600',
        availableSlot: 'Home Collection Available',
        isLowestPrice: false,
        isFastestReport: false,
      },
    ],
  },
  {
    testId: 'cmp-path-2',
    testName: 'Lipid Profile Comprehensive (Cardio Panel)',
    category: 'pathology',
    description: 'Essential cardiac risk assessment measuring Total Cholesterol, HDL, LDL, Triglycerides, and VLDL.',
    centers: [
      {
        centerId: 'c6',
        centerName: 'Bhagyodaya Central Laboratory',
        centerType: 'Hospital Diagnostic Lab',
        locality: 'Khurai Road, Sagar',
        distanceKm: 2.1,
        rating: 4.95,
        accreditation: 'Automated Biochemical Analyzer',
        mrp: 850,
        price: 399,
        savings: 451,
        turnaroundTime: 'Same Day by 2 PM',
        phone: '07582-472000',
        availableSlot: 'Fasting Slot 07:00 - 11:00 AM',
        isLowestPrice: true,
        isFastestReport: true,
      },
      {
        centerId: 'c5',
        centerName: 'Apollo Diagnostics Sagar',
        centerType: 'National NABL Laboratory',
        locality: 'Civil Lines, Sagar',
        distanceKm: 2.8,
        rating: 4.92,
        accreditation: 'NABL Certified Direct Reporting',
        mrp: 900,
        price: 449,
        savings: 451,
        turnaroundTime: '4 Hours',
        phone: '07582-249911',
        availableSlot: 'Home Collection at 08:00 AM',
        isLowestPrice: false,
        isFastestReport: false,
      },
      {
        centerId: 'c7',
        centerName: 'Dr. Lal PathLabs Sagar',
        centerType: 'National Reference Lab',
        locality: 'Gujarati Bazar, Sagar',
        distanceKm: 3.9,
        rating: 4.94,
        accreditation: 'CAP & NABL Certified',
        mrp: 950,
        price: 520,
        savings: 430,
        turnaroundTime: '5 Hours',
        phone: '07582-225600',
        availableSlot: 'Fasting Slot 07:30 AM',
        isLowestPrice: false,
        isFastestReport: false,
      },
    ],
  },
  {
    testId: 'cmp-xray-1',
    testName: 'Digital Chest X-Ray (PA View DR Film)',
    category: 'x_ray',
    description: 'High-definition digital radiography of chest, lungs, ribs, and mediastinum with instant digital radiologist analysis.',
    centers: [
      {
        centerId: 'c1',
        centerName: 'Bhagyodaya Tirth Radiology Unit',
        centerType: 'Super Specialty Hospital',
        locality: 'Khurai Road, Sagar',
        distanceKm: 2.1,
        rating: 4.96,
        accreditation: '100% Direct Digital Flat Panel DR',
        mrp: 600,
        price: 299,
        savings: 301,
        turnaroundTime: '20 Mins Instant Delivery',
        phone: '07582-472000',
        availableSlot: 'Immediate Token Walk-In',
        isLowestPrice: true,
        isFastestReport: true,
      },
      {
        centerId: 'c2',
        centerName: 'Bansal Imaging Center',
        centerType: 'Dedicated Radiology Centre',
        locality: 'Civil Lines, Sagar',
        distanceKm: 3.4,
        rating: 4.91,
        accreditation: 'Computed Radiography High Dynamic Range',
        mrp: 650,
        price: 349,
        savings: 301,
        turnaroundTime: '30 Mins',
        phone: '07582-401122',
        availableSlot: 'Walk-In Available',
        isLowestPrice: false,
        isFastestReport: false,
      },
      {
        centerId: 'c8',
        centerName: 'Sagar Advanced X-Ray Clinic',
        centerType: 'Orthopedic Diagnostic Centre',
        locality: 'Deendayal Nagar, Sagar',
        distanceKm: 4.5,
        rating: 4.88,
        accreditation: 'AERB Certified Low-Radiation',
        mrp: 700,
        price: 399,
        savings: 301,
        turnaroundTime: '30 Mins',
        phone: '07582-243388',
        availableSlot: 'Walk-In Available',
        isLowestPrice: false,
        isFastestReport: false,
      },
    ],
  },
];

export interface HospitalAmenityItem {
  id: string;
  name: string;
  category: 'emergency' | 'icu' | 'imaging' | 'dialysis' | 'blood_bank' | 'surgical' | 'general';
  centerName: string;
  locality: string;
  ratingAverage: number;
  availability: string;
  badge: string;
  phone: string;
  imageUrl: string;
  description: string;
  features: string[];
}

export const initialHospitalAmenities: HospitalAmenityItem[] = [
  {
    id: 'am-1',
    name: '24x7 Emergency & Trauma Resuscitation Center',
    category: 'emergency',
    centerName: 'Bhagyodaya Tirth Hospital & Research Centre',
    locality: 'Khurai Road, Sagar',
    ratingAverage: 4.96,
    availability: 'Open 24x7 • Zero Wait Emergency OPD',
    badge: 'Level 1 Trauma Care',
    phone: '07582-472000',
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=500&auto=format&fit=crop&q=80',
    description: 'Dedicated ACLS ambulances, dedicated critical care triage, emergency defibrillation, and on-duty trauma surgeons.',
    features: ['24/7 On-Call Surgeons', 'Dedicated Resuscitation Bay', 'Emergency OT Ready', 'GPS Tracked Ambulances']
  },
  {
    id: 'am-2',
    name: '32-Bed Multi-Specialty ICU / NICU / PICU',
    category: 'icu',
    centerName: 'Bansal Hospital Sagar',
    locality: 'Civil Lines, Sagar',
    ratingAverage: 4.94,
    availability: '24x7 Intensivist On-Duty',
    badge: 'Class 100 HEPA Cleanroom',
    phone: '07582-401122',
    imageUrl: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=500&auto=format&fit=crop&q=80',
    description: 'High-end Dräger ventilators, central multi-para hemodynamic monitors, isolation beds, and dedicated pediatric incubators.',
    features: ['1:1 Nursing Ratio', 'Dräger High-End Ventilators', 'Isolation Negative Pressure', 'ABG Blood Gas Lab Inside']
  },
  {
    id: 'am-3',
    name: 'Fresenius High-Flux Hemodialysis Unit',
    category: 'dialysis',
    centerName: 'Sagar City Dialysis & Renal Institute',
    locality: 'Deendayal Nagar, Sagar',
    ratingAverage: 4.91,
    availability: 'Slots: 6:00 AM – 10:00 PM Daily',
    badge: 'Bicarbonate RO Dialysis',
    phone: '07582-243388',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=500&auto=format&fit=crop&q=80',
    description: 'Ultra-pure water treatment plant, computerized dialyzer reprocessing, and on-site nephrologist supervision.',
    features: ['Fresenius 4008S Machines', 'Reclining Electronic Beds', 'Heparin Infusion Pumps', 'Zero Cross-Infection Protocol']
  },
  {
    id: 'am-4',
    name: '24x7 Voluntary Blood Bank & Component Separation',
    category: 'blood_bank',
    centerName: 'BMC Government Medical College Blood Bank',
    locality: 'Medical College, Sagar',
    ratingAverage: 4.88,
    availability: 'Open 24 Hours • ABHA Linked',
    badge: 'PRBC, FFP & Platelet Cryo',
    phone: '07582-234500',
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=500&auto=format&fit=crop&q=80',
    description: 'FDA certified component separation for Packed Red Blood Cells (PRBC), Single Donor Platelets (SDP), and Fresh Frozen Plasma (FFP).',
    features: ['ID-NAT Tested Safe Blood', 'Cryo-Centrifuge Separation', 'Walk-in Replacement Issue', 'Direct Donor App Check']
  },
  {
    id: 'am-5',
    name: 'Digital Cardiac Catheterization Lab (Cath Lab)',
    category: 'surgical',
    centerName: 'Bhagyodaya Tirth Cardiac Institute',
    locality: 'Khurai Road, Sagar',
    ratingAverage: 4.97,
    availability: 'Primary Angioplasty 24x7',
    badge: 'Siemens Artis Flat-Panel',
    phone: '07582-472000',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=500&auto=format&fit=crop&q=80',
    description: 'Sub-millimeter radial angiography, drug-eluting stent implantation, fractional flow reserve (FFR), and permanent pacemaker implants.',
    features: ['< 60 Min Door-to-Balloon Time', 'IVUS & OCT Intravascular Imaging', 'Permanent Pacemaker Implants', 'Intra-Aortic Balloon Pump (IABP)']
  },
  {
    id: 'am-6',
    name: '1.5-Tesla Silent MRI & 3D MR-Angiography',
    category: 'imaging',
    centerName: 'Sagar Advanced Imaging & Scan Hub',
    locality: 'Civil Lines, Sagar',
    ratingAverage: 4.93,
    availability: '8:00 AM – 9:00 PM (Emergency 24x7)',
    badge: 'Acoustic Noise Reduction',
    phone: '07582-401122',
    imageUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=500&auto=format&fit=crop&q=80',
    description: 'Whole body diffusion MRI, Brain Stroke DWI/DTI mapping, Knee and Spine 3D cartilage imaging with ultra-fast acquisition.',
    features: ['Wide 70cm Bore (Claustrophobia Free)', 'Silent Scan Noise Dampening', 'Dedicated Pediatric MRI Protocol', 'Same-Day Radiologist Reports']
  }
];
