import {
  UserProfile,
  FamilyMember,
  EmergencyProfile,
  Doctor,
  Hospital,
  Medicine,
  Pharmacy,
  MedicationSchedule,
  MedicationLog,
  Appointment,
  MedicalDocument,
  BiomarkerReportItem,
  LabTest,
  LabBooking,
  HealthcareExpense,
  PharmacyOrder,
  HealthNotification,
  HealthInboxItem
} from '../types';

export const initialUserProfile: UserProfile = {
  id: 'usr-101',
  userId: 'auth-001',
  firstName: 'Arjun',
  lastName: 'Sharma',
  email: 'arjun.sharma@example.com',
  phone: '+91 98765 43210',
  dateOfBirth: '1988-06-14',
  gender: 'male',
  bloodGroup: 'B+',
  abhaId: '14-5521-9874-2201',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  heightCm: 176,
  weightKg: 74.5,
  createdAt: '2025-01-10T10:00:00Z',
};

export const initialFamilyMembers: FamilyMember[] = [
  {
    id: 'fam-1',
    primaryUserProfileId: 'usr-101',
    fullName: 'Savitri Sharma',
    relationship: 'parent',
    dateOfBirth: '1959-03-22',
    gender: 'female',
    bloodGroup: 'O+',
    abhaId: '14-1189-3321-4490',
    permissionLevel: 'full_proxy',
    permissions: [
      'VIEW_APPOINTMENTS',
      'BOOK_APPOINTMENTS',
      'VIEW_MEDICATIONS',
      'MANAGE_MEDICATIONS',
      'VIEW_RECORDS',
      'UPLOAD_RECORDS',
      'VIEW_EXPENSES',
      'EMERGENCY_ACCESS'
    ],
    chronicConditions: ['Primary Hypertension', 'Osteoarthritis'],
    allergies: ['Dust', 'Shellfish'],
    emergencyContact: '+91 98110 12345',
    notes: 'Hypertension and Osteoarthritis. Requires daily medication supervision.',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'fam-2',
    primaryUserProfileId: 'usr-101',
    fullName: 'Ramesh Sharma',
    relationship: 'parent',
    dateOfBirth: '1954-11-08',
    gender: 'male',
    bloodGroup: 'B+',
    abhaId: '14-9981-6672-1102',
    permissionLevel: 'full_proxy',
    permissions: [
      'VIEW_APPOINTMENTS',
      'BOOK_APPOINTMENTS',
      'VIEW_MEDICATIONS',
      'MANAGE_MEDICATIONS',
      'VIEW_RECORDS',
      'UPLOAD_RECORDS',
      'VIEW_EXPENSES',
      'EMERGENCY_ACCESS'
    ],
    chronicConditions: ['Type 2 Diabetes Mellitus', 'Coronary Artery Stent (2021)'],
    allergies: ['Sulfa Drugs'],
    emergencyContact: '+91 98110 12345',
    notes: 'Type-2 Diabetes and Mild Cardiac Stent in 2021.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'fam-3',
    primaryUserProfileId: 'usr-101',
    fullName: 'Aarav Sharma',
    relationship: 'child',
    dateOfBirth: '2018-09-12',
    gender: 'male',
    bloodGroup: 'B+',
    permissionLevel: 'full_proxy',
    permissions: [
      'VIEW_APPOINTMENTS',
      'BOOK_APPOINTMENTS',
      'VIEW_MEDICATIONS',
      'MANAGE_MEDICATIONS',
      'VIEW_RECORDS',
      'UPLOAD_RECORDS',
      'EMERGENCY_ACCESS'
    ],
    chronicConditions: ['Childhood Asthma'],
    allergies: ['Peanuts'],
    vaccinationsDue: [
      {
        vaccineName: 'MMR Booster (Measles, Mumps, Rubella)',
        dueDate: '2026-09-15',
        status: 'due'
      }
    ],
    notes: 'Mild seasonal asthma and dust allergy.',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80'
  }
];

export const initialEmergencyProfile: EmergencyProfile = {
  id: 'emg-001',
  userProfileId: 'usr-101',
  fullName: 'Arjun Sharma',
  bloodGroup: 'B+',
  dateOfBirth: '1988-06-14',
  allergies: ['Penicillin', 'Sulfa Drugs'],
  chronicConditions: ['Mild Asthma', 'Allergic Rhinitis'],
  currentMedicationsSummary: ['Montelukast 10mg (Night)', 'Levocetirizine 5mg (SOS)'],
  implantedDevices: ['None'],
  organDonor: true,
  emergencyContacts: [
    {
      id: 'ec-1',
      name: 'Priya Sharma',
      relationship: 'Spouse',
      phone: '+91 98765 88990',
      isPrimary: true
    },
    {
      id: 'ec-2',
      name: 'Dr. Vivek Mehra (Family Physician)',
      relationship: 'Doctor',
      phone: '+91 98110 12345',
      isPrimary: false
    }
  ],
  publicEmergencyToken: 'emg_tok_8f93a7c1b2',
  requiresPin: false,
  updatedAt: '2026-08-20T14:30:00Z'
};

export const initialDoctors: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Ananya Roy',
    title: 'Senior Consultant Cardiologist',
    specialization: 'Cardiology',
    qualification: 'MBBS, MD (Medicine), DM (Cardiology)',
    experienceYears: 16,
    consultationFee: 1200,
    ratingAverage: 4.9,
    ratingCount: 342,
    patientCount: '4.8k+',
    reviewsCount: '2.4k',
    languages: ['English', 'Hindi', 'Bengali'],
    consultationTypes: ['in_person', 'video_teleconsult'],
    hospitalName: 'Apollo Heart & Multispeciality Institute',
    clinicAddress: 'Room 304, OPD Block, Apollo Hospital, South Extension',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&auto=format&fit=crop&q=80',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    availableSlots: ['09:00 AM', '09:30 AM', '10:30 AM', '11:00 AM', '02:30 PM', '03:30 PM', '05:00 PM', '06:00 PM'],
    isVerified: true,
    about: 'Specialist in non-invasive cardiology, preventive heart care, hypertension management, and advanced echocardiography with over 16 years of clinical excellence.'
  },
  {
    id: 'doc-2',
    name: 'Dr. Rajesh Deshmukh',
    title: 'Chief Endocrinologist & Diabetologist',
    specialization: 'Endocrinology',
    qualification: 'MBBS, MD, FRCP (UK)',
    experienceYears: 21,
    consultationFee: 1000,
    ratingAverage: 4.8,
    ratingCount: 512,
    patientCount: '6.2k+',
    reviewsCount: '3.1k',
    languages: ['English', 'Hindi', 'Marathi'],
    consultationTypes: ['in_person', 'video_teleconsult'],
    hospitalName: 'Fortis Health Center',
    clinicAddress: 'OPD 12, Fortis Hospital, Sector 62',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=500&auto=format&fit=crop&q=80',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Saturday'],
    availableSlots: ['10:00 AM', '10:30 AM', '11:30 AM', '02:00 PM', '03:00 PM', '04:30 PM', '05:30 PM'],
    isVerified: true,
    about: 'Leading authority on complex metabolic disorders, gestational diabetes, insulin pumps, and thyroid hormone management.'
  },
  {
    id: 'doc-3',
    name: 'Dr. Meera Nambiar',
    title: 'Consultant Pediatrician & Neonatologist',
    specialization: 'Pediatrics',
    qualification: 'MBBS, DCH, DNB (Pediatrics)',
    experienceYears: 12,
    consultationFee: 800,
    ratingAverage: 4.95,
    ratingCount: 280,
    patientCount: '3.5k+',
    reviewsCount: '1.9k',
    languages: ['English', 'Hindi', 'Malayalam', 'Kannada'],
    consultationTypes: ['in_person', 'video_teleconsult'],
    hospitalName: 'Mother & Child Care Hospital',
    clinicAddress: 'Clinic 2, Mother Care Clinic, Indiranagar',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813501-4843516ff8ef?w=500&auto=format&fit=crop&q=80',
    availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
    availableSlots: ['09:00 AM', '09:45 AM', '10:30 AM', '11:15 AM', '04:00 PM', '05:00 PM', '06:00 PM'],
    isVerified: true,
    about: 'Warm and gentle pediatrician focusing on child growth milestones, developmental immunology, and pediatric nutrition.'
  },
  {
    id: 'doc-4',
    name: 'Dr. Siddharth Verma',
    title: 'Senior Orthopedic Surgeon',
    specialization: 'Orthopedics',
    qualification: 'MBBS, MS (Ortho), MCh (Joint Replacement)',
    experienceYears: 18,
    consultationFee: 1100,
    ratingAverage: 4.85,
    ratingCount: 410,
    patientCount: '5.1k+',
    reviewsCount: '2.7k',
    languages: ['English', 'Hindi', 'Punjabi'],
    consultationTypes: ['in_person', 'video_teleconsult'],
    hospitalName: 'Max Super Speciality Hospital',
    clinicAddress: 'Joint Care Wing, Max Hospital, Saket',
    avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=500&auto=format&fit=crop&q=80',
    availableDays: ['Tuesday', 'Thursday', 'Saturday'],
    availableSlots: ['10:30 AM', '11:15 AM', '12:00 PM', '02:00 PM', '03:00 PM', '05:00 PM'],
    isVerified: true,
    about: 'Specializes in robotic knee & hip arthroplasty, sports ligament repairs, spinal decompression, and geriatric arthritis management.'
  },
  {
    id: 'doc-5',
    name: 'Dr. Retna Rasa',
    title: 'Senior Neurosurgeon & Spine Specialist',
    specialization: 'Neurology',
    qualification: 'MBBS, MS, MCh (Neurosurgery), FINR (Zurich)',
    experienceYears: 19,
    consultationFee: 1500,
    ratingAverage: 4.95,
    ratingCount: 640,
    patientCount: '7.8k+',
    reviewsCount: '3.9k',
    languages: ['English', 'Hindi', 'Tamil'],
    consultationTypes: ['in_person', 'video_teleconsult'],
    hospitalName: 'Apollo Multispeciality & Emergency Center',
    clinicAddress: 'Brain & Spine Suite 4, Apollo Hospital, Sarita Vihar',
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=500&auto=format&fit=crop&q=80',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['09:00 AM', '09:30 AM', '10:00 AM', '11:30 AM', '03:00 PM', '04:00 PM', '06:00 PM'],
    isVerified: true,
    about: 'Internationally recognized neurosurgeon specializing in minimally invasive brain surgery, epilepsy mapping, and cervical spine reconstruction.'
  },
  {
    id: 'doc-6',
    name: 'Dr. Ethan Brooks',
    title: 'Lead Dental & Maxillofacial Surgeon',
    specialization: 'Dental Care',
    qualification: 'BDS, MDS (Orthodontics & Implants)',
    experienceYears: 14,
    consultationFee: 750,
    ratingAverage: 4.9,
    ratingCount: 380,
    patientCount: '4.2k+',
    reviewsCount: '2.1k',
    languages: ['English', 'Hindi'],
    consultationTypes: ['in_person', 'video_teleconsult'],
    hospitalName: 'Aarogya Dental & Ortho Studio',
    clinicAddress: 'Shop 14, Main Market, Green Park, New Delhi',
    avatarUrl: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=500&auto=format&fit=crop&q=80',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Friday', 'Saturday'],
    availableSlots: ['10:00 AM', '11:00 AM', '12:00 PM', '04:00 PM', '05:00 PM', '07:00 PM'],
    isVerified: true,
    about: 'Specialist in digital smile design, painless root canals, invisible aligners, and single-visit titanium dental implants.'
  },
  {
    id: 'doc-7',
    name: 'Dr. Kevin Holcomb',
    title: 'Senior Gynecologist & Fertility Specialist',
    specialization: 'Gynecology',
    qualification: 'MBBS, MD (OB-GYN), DGO, FICOG',
    experienceYears: 22,
    consultationFee: 1300,
    ratingAverage: 4.85,
    ratingCount: 490,
    patientCount: '8.1k+',
    reviewsCount: '4.3k',
    languages: ['English', 'Hindi', 'Bengali'],
    consultationTypes: ['in_person', 'video_teleconsult'],
    hospitalName: 'Max Smart Super Speciality Hospital',
    clinicAddress: 'Women & Child OPD, Max Hospital, Saket',
    avatarUrl: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=500&auto=format&fit=crop&q=80',
    availableDays: ['Monday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    availableSlots: ['09:30 AM', '10:30 AM', '11:30 AM', '02:30 PM', '03:30 PM', '05:30 PM'],
    isVerified: true,
    about: 'Expert in high-risk pregnancy care, robotic laparoscopic gynecological surgery, PCOD management, and IVF reproductive health.'
  },
  {
    id: 'doc-8',
    name: 'Dr. Norman Latov',
    title: 'Consultant Dermatologist & Cosmetologist',
    specialization: 'Dermatology',
    qualification: 'MBBS, MD (Dermatology, Venereology & Leprosy)',
    experienceYears: 15,
    consultationFee: 900,
    ratingAverage: 4.9,
    ratingCount: 320,
    patientCount: '5.6k+',
    reviewsCount: '2.8k',
    languages: ['English', 'Hindi'],
    consultationTypes: ['in_person', 'video_teleconsult'],
    hospitalName: 'Skin & Laser Clinical Center',
    clinicAddress: 'Building 8, Green Park Extension, New Delhi',
    avatarUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=500&auto=format&fit=crop&q=80',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Friday', 'Saturday'],
    availableSlots: ['11:00 AM', '12:00 PM', '02:00 PM', '04:00 PM', '05:30 PM', '06:30 PM'],
    isVerified: true,
    about: 'Advanced clinical dermatology, acne scar laser treatments, eczema therapies, and holistic hair restoration solutions.'
  }
];

export const initialHospitals: Hospital[] = [
  {
    id: 'hosp-1',
    name: 'Apollo Multispeciality & Emergency Center',
    type: 'Super Specialty',
    address: 'Sarita Vihar, Mathura Road, New Delhi',
    city: 'New Delhi',
    distanceKm: 3.2,
    emergencyHelpline: '1066 / +91 11 2692 5858',
    has24x7Emergency: true,
    icuBedsAvailable: 14,
    totalBeds: 450,
    rating: 4.8,
    facilities: ['24/7 Level 1 Trauma Care', 'Cardiac ICU', 'Advanced Stroke Unit', 'Robotic Surgery', 'Blood Bank'],
    imageUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'hosp-2',
    name: 'Fortis Memorial Health Institute',
    type: 'Multispecialty',
    address: 'Sector 44, Opposite City Centre',
    city: 'Gurugram',
    distanceKm: 5.8,
    emergencyHelpline: '105010 / +91 124 4962200',
    has24x7Emergency: true,
    icuBedsAvailable: 9,
    totalBeds: 380,
    rating: 4.7,
    facilities: ['24/7 Emergency ER', 'Pediatric ICU', 'Comprehensive Cancer Center', 'Dialysis Unit'],
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'hosp-3',
    name: 'Max Smart Super Speciality Hospital',
    type: 'Super Specialty',
    address: 'Press Enclave Road, Saket',
    city: 'New Delhi',
    distanceKm: 4.1,
    emergencyHelpline: '011-40554055',
    has24x7Emergency: true,
    icuBedsAvailable: 18,
    totalBeds: 500,
    rating: 4.9,
    facilities: ['Trauma Center', 'Neuroscience Center', 'Heart Valve Clinic', 'Advanced Diagnostics'],
    imageUrl: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=500&auto=format&fit=crop&q=80'
  }
];

export const initialMedicines: Medicine[] = [
  // --- PAIN & FEVER RELIEF ---
  {
    id: 'med-7',
    brandName: 'Dolo 650 Tablet',
    genericName: 'Paracetamol Tablets IP 650mg',
    form: 'tablet',
    strength: '1 Strip (15 Tablets)',
    category: 'otc_wellness',
    manufacturer: 'Micro Labs Ltd',
    price: 32,
    mrp: 35,
    discountPercent: 8,
    prescriptionRequired: false,
    rating: 4.95,
    ratingCount: 4500,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 300,
    description: 'Fast-acting fever and pain relief tablets. Suitable for viral fever, headache, body ache and toothache.'
  },
  {
    id: 'med-9',
    brandName: 'Combiflam Tablet',
    genericName: 'Ibuprofen (400mg) + Paracetamol (325mg)',
    form: 'tablet',
    strength: '1 Strip (20 Tablets)',
    category: 'otc_wellness',
    manufacturer: 'Sanofi India Ltd',
    price: 42,
    mrp: 48,
    discountPercent: 12,
    prescriptionRequired: false,
    rating: 4.88,
    ratingCount: 2800,
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 240,
    description: 'Dual-action pain relief for severe headache, muscle spasms, dental pain, and joint stiffness.'
  },
  {
    id: 'med-10',
    brandName: 'Saridon Headache Relief',
    genericName: 'Paracetamol (250mg) + Propyphenazone (150mg) + Caffeine (50mg)',
    form: 'tablet',
    strength: '1 Strip (10 Tablets)',
    category: 'otc_wellness',
    manufacturer: 'Bayer Healthcare',
    price: 45,
    mrp: 50,
    discountPercent: 10,
    prescriptionRequired: false,
    rating: 4.85,
    ratingCount: 3100,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 180,
    description: 'Trusted 3-action formula for quick headache, migraine, and mental fatigue relief in 15 minutes.'
  },
  {
    id: 'med-8',
    brandName: 'Volini Pain Relief Gel',
    genericName: 'Diclofenac Diethylamine, Methyl Salicylate & Menthol',
    form: 'ointment',
    strength: '75g Tube',
    category: 'must_haves',
    manufacturer: 'Sun Pharma',
    price: 130,
    mrp: 155,
    discountPercent: 16,
    prescriptionRequired: false,
    rating: 4.8,
    ratingCount: 920,
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 80,
    description: 'Deep penetrating nanogel formula for instant relief from neck, shoulder, back, and joint sprains.'
  },
  {
    id: 'med-11',
    brandName: 'Moov Fast Pain Relief Spray',
    genericName: '100% Ayurvedic Pain Relief Active Spray',
    form: 'drops',
    strength: '50g Spray Can',
    category: 'must_haves',
    manufacturer: 'Reckitt Benckiser',
    price: 165,
    mrp: 185,
    discountPercent: 11,
    prescriptionRequired: false,
    rating: 4.75,
    ratingCount: 1400,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 110,
    description: 'Quick action pain relief spray made with Nilgiri oil, Wintergreen oil, and Mint extracts.'
  },

  // --- COLD, COUGH & ALLERGIES ---
  {
    id: 'med-12',
    brandName: 'Vicks VapoRub',
    genericName: 'Menthol, Camphor & Eucalyptus Oil Ointment',
    form: 'ointment',
    strength: '50ml Jar',
    category: 'must_haves',
    manufacturer: 'Procter & Gamble',
    price: 145,
    mrp: 160,
    discountPercent: 9,
    prescriptionRequired: false,
    rating: 4.92,
    ratingCount: 5400,
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 220,
    description: 'Provides 8 hours of multi-symptom relief from cold, cough, blocked nose, and breathing congestion.'
  },
  {
    id: 'med-13',
    brandName: 'Otrivin Oxy Fast Relief Nasal Spray',
    genericName: 'Oxymetazoline Hydrochloride Nasal Solution (0.05%)',
    form: 'drops',
    strength: '10ml Spray Bottle',
    category: 'otc_wellness',
    manufacturer: 'GSK Consumer Healthcare',
    price: 108,
    mrp: 120,
    discountPercent: 10,
    prescriptionRequired: false,
    rating: 4.86,
    ratingCount: 1650,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 140,
    description: 'Unblocks stuffy nose in 25 seconds and keeps nasal airways clear for up to 12 hours.'
  },
  {
    id: 'med-14',
    brandName: 'Strepsils Honey & Lemon Lozenges',
    genericName: 'Dichlorobenzyl Alcohol + Amylmetacresol',
    form: 'tablet',
    strength: '1 Strip (8 Lozenges)',
    category: 'otc_wellness',
    manufacturer: 'Reckitt Benckiser',
    price: 38,
    mrp: 42,
    discountPercent: 10,
    prescriptionRequired: false,
    rating: 4.88,
    ratingCount: 2900,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 400,
    description: 'Double antibacterial action for soothing sore throats and irritating dry cough tickles.'
  },
  {
    id: 'med-3',
    brandName: 'Montair LC',
    genericName: 'Montelukast Sodium 10mg + Levocetirizine 5mg',
    form: 'tablet',
    strength: '1 Strip (10 Tablets)',
    category: 'chronic_care',
    manufacturer: 'Cipla Ltd',
    price: 204,
    mrp: 255,
    discountPercent: 20,
    prescriptionRequired: true,
    rating: 4.7,
    ratingCount: 890,
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 120,
    description: 'Relieves symptoms of allergic rhinitis, seasonal allergies, sneezing, runny nose, and asthma.'
  },

  // --- FIRST AID & ANTISEPTIC ---
  {
    id: 'med-15',
    brandName: 'Dettol Antiseptic Liquid',
    genericName: 'Chloroxylenol (4.8% w/v) Antiseptic Solution',
    form: 'syrup',
    strength: '250ml Bottle',
    category: 'must_haves',
    manufacturer: 'Reckitt Benckiser',
    price: 135,
    mrp: 150,
    discountPercent: 10,
    prescriptionRequired: false,
    rating: 4.95,
    ratingCount: 6800,
    imageUrl: 'https://images.unsplash.com/photo-1584744982491-665216d95f8b?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 190,
    description: 'Trusted antiseptic liquid for first aid wound cleansing, minor cuts, bites, and personal hygiene.'
  },
  {
    id: 'med-16',
    brandName: 'Band-Aid Washproof Strips',
    genericName: 'Medical Grade Adhesive Wound Bandages',
    form: 'ointment',
    strength: 'Pack of 20 Strips',
    category: 'must_haves',
    manufacturer: 'Johnson & Johnson',
    price: 55,
    mrp: 65,
    discountPercent: 15,
    prescriptionRequired: false,
    rating: 4.89,
    ratingCount: 3400,
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 250,
    description: 'Water-resistant, breathable sterile bandages with Quilt-Aid padding for quick healing.'
  },
  {
    id: 'med-17',
    brandName: 'Betadine 10% Antiseptic Ointment',
    genericName: 'Povidone Iodine Ointment IP 10%',
    form: 'ointment',
    strength: '20g Tube',
    category: 'must_haves',
    manufacturer: 'Win-Medicare',
    price: 115,
    mrp: 130,
    discountPercent: 12,
    prescriptionRequired: false,
    rating: 4.9,
    ratingCount: 1250,
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 85,
    description: 'Broad spectrum microbicidal ointment for prevention and treatment of skin infections in minor burns and abrasions.'
  },

  // --- STOMACH & DIGESTION ---
  {
    id: 'med-18',
    brandName: 'Eno Regular Fruit Salt',
    genericName: 'Svarjiksara (51.8%) + Nimbukamlam (48.2%)',
    form: 'powder',
    strength: '100g Bottle',
    category: 'otc_wellness',
    manufacturer: 'GSK Consumer Healthcare',
    price: 140,
    mrp: 155,
    discountPercent: 10,
    prescriptionRequired: false,
    rating: 4.94,
    ratingCount: 4100,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 210,
    description: 'Works in 6 seconds to neutralize stomach acid and relieve acidity, reflux, and bloating.'
  },
  {
    id: 'med-19',
    brandName: 'Digene Gel Mint Flavour',
    genericName: 'Magnesium Hydroxide, Aluminium Hydroxide & Simethicone',
    form: 'syrup',
    strength: '200ml Bottle',
    category: 'otc_wellness',
    manufacturer: 'Abbott Healthcare',
    price: 142,
    mrp: 165,
    discountPercent: 14,
    prescriptionRequired: false,
    rating: 4.88,
    ratingCount: 1950,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 130,
    description: 'Sugar-free antacid gel with soothing mint cooling for long-lasting acidity and gas relief.'
  },
  {
    id: 'med-20',
    brandName: 'Electral ORS Powder',
    genericName: 'WHO Recommended Oral Rehydration Salts',
    form: 'powder',
    strength: '21.8g Sachet',
    category: 'must_haves',
    manufacturer: 'FDC Limited',
    price: 22,
    mrp: 24,
    discountPercent: 8,
    prescriptionRequired: false,
    rating: 4.96,
    ratingCount: 5200,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 500,
    description: 'Restores essential body fluids and electrolytes lost due to dehydration, heat stroke, or diarrhea.'
  },

  // --- DAILY VITAMINS & NUTRITION ---
  {
    id: 'med-6',
    brandName: 'Shelcal 500',
    genericName: 'Elemental Calcium (500mg) + Vitamin D3 (250 IU)',
    form: 'tablet',
    strength: '1 Strip (15 Tablets)',
    category: 'must_haves',
    manufacturer: 'Torrent Pharmaceuticals',
    price: 118,
    mrp: 135,
    discountPercent: 12,
    prescriptionRequired: false,
    rating: 4.75,
    ratingCount: 1100,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 150,
    description: 'Dietary supplement to maintain healthy bone mineral density, joint strength, and calcium levels.'
  },
  {
    id: 'med-21',
    brandName: 'Becosules Z Multivitamin Capsules',
    genericName: 'Vitamin B-Complex Forte with Vitamin C and Zinc',
    form: 'capsule',
    strength: '1 Strip (20 Capsules)',
    category: 'must_haves',
    manufacturer: 'Pfizer India',
    price: 48,
    mrp: 55,
    discountPercent: 13,
    prescriptionRequired: false,
    rating: 4.88,
    ratingCount: 3200,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 280,
    description: 'Helps in boosting energy metabolism, immunity, treating mouth ulcers, and improving skin texture.'
  },
  {
    id: 'med-22',
    brandName: 'Limcee 500mg Vitamin C Chewable',
    genericName: 'Ascorbic Acid (100mg) + Sodium Ascorbate (450mg)',
    form: 'tablet',
    strength: '1 Strip (15 Chewables)',
    category: 'must_haves',
    manufacturer: 'Abbott Healthcare',
    price: 24,
    mrp: 28,
    discountPercent: 14,
    prescriptionRequired: false,
    rating: 4.93,
    ratingCount: 4900,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 350,
    description: 'Tasty orange chewable Vitamin C tablets for antioxidant support, radiant skin, and daily immunity.'
  },
  {
    id: 'med-23',
    brandName: 'Evion 400 Vitamin E Capsules',
    genericName: 'Tocopheryl Acetate (Vitamin E) IP 400mg',
    form: 'capsule',
    strength: '1 Strip (10 Capsules)',
    category: 'skin_care',
    manufacturer: 'Procter & Gamble',
    price: 36,
    mrp: 40,
    discountPercent: 10,
    prescriptionRequired: false,
    rating: 4.91,
    ratingCount: 3800,
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 220,
    description: 'Essential Vitamin E for deep skin nourishment, hair nourishment, and healthy cell growth.'
  },

  // --- SKINCARE & BODY ESSENTIALS ---
  {
    id: 'med-1',
    brandName: 'Cetaphil Gentle Skin Cleanser',
    genericName: 'Hydrating Face Wash for Sensitive Skin',
    form: 'cleanser',
    strength: '125ml Bottle',
    category: 'skin_care',
    manufacturer: 'Galderma India',
    price: 341,
    mrp: 428,
    discountPercent: 20,
    prescriptionRequired: false,
    rating: 4.8,
    ratingCount: 1420,
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 45,
    description: 'Dermatologist-recommended soap-free gentle cleanser for dry to normal, sensitive skin.'
  },
  {
    id: 'med-2',
    brandName: 'CeraVe Moisturising Lotion',
    genericName: 'Essential Ceramides + Hyaluronic Acid',
    form: 'lotion',
    strength: '473ml Dispenser Bottle',
    category: 'skin_care',
    manufacturer: "L'Oréal India",
    price: 1440,
    mrp: 1600,
    discountPercent: 10,
    prescriptionRequired: false,
    rating: 4.9,
    ratingCount: 2310,
    imageUrl: 'https://images.unsplash.com/photo-1608248597359-5984687b8764?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 28,
    description: 'Lightweight daily moisturizer with 3 essential ceramides for 24-hour barrier hydration.'
  },

  // --- CHRONIC & HEART CARE (PRESCRIPTION) ---
  {
    id: 'med-4',
    brandName: 'Telma 40',
    genericName: 'Telmisartan Tablets IP 40mg',
    form: 'tablet',
    strength: '1 Strip (15 Tablets)',
    category: 'chronic_care',
    manufacturer: 'Glenmark Pharmaceuticals',
    price: 185,
    mrp: 210,
    discountPercent: 12,
    prescriptionRequired: true,
    rating: 4.85,
    ratingCount: 650,
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 95,
    description: 'Angiotensin receptor blocker used for primary hypertension and cardiovascular risk reduction.'
  },
  {
    id: 'med-5',
    brandName: 'Augmentin 625 Duo',
    genericName: 'Amoxicillin (500mg) + Clavulanic Acid (125mg)',
    form: 'tablet',
    strength: '1 Strip (10 Tablets)',
    category: 'medicines',
    manufacturer: 'GSK India',
    price: 204,
    mrp: 232,
    discountPercent: 12,
    prescriptionRequired: true,
    rating: 4.9,
    ratingCount: 520,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 60,
    description: 'Broad-spectrum penicillin antibiotic for bacterial respiratory, skin, and ENT infections.'
  },
  {
    id: 'med-24',
    brandName: 'Glycomet GP2 Tablet',
    genericName: 'Glimepiride (2mg) + Metformin (500mg)',
    form: 'tablet',
    strength: '1 Strip (15 Tablets)',
    category: 'chronic_care',
    manufacturer: 'USV Private Limited',
    price: 198,
    mrp: 230,
    discountPercent: 14,
    prescriptionRequired: true,
    rating: 4.82,
    ratingCount: 910,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&auto=format&fit=crop&q=80',
    inStock: true,
    stockQuantity: 110,
    description: 'Dual anti-diabetic medicine prescribed for glycemic control in Type 2 Diabetes Mellitus.'
  }
];

export const initialPharmacies: Pharmacy[] = [
  {
    id: 'pharma-1',
    name: 'Apollo 24|7 Express Pharmacy',
    address: 'A-14, Green Park Main Market, New Delhi',
    distanceKm: 0.8,
    rating: 4.8,
    isOpen24x7: true,
    phone: '+91 11 4165 8899',
    estimatedDeliveryMins: 25,
    deliveryFee: 0,
    operatingHours: '24 Hours (All 7 Days)',
    deliveryRadiusKm: 8.5,
    licenseNumber: 'DL-2026-PHA-88192'
  },
  {
    id: 'pharma-2',
    name: 'MedPlus Superstore & Pharmacy',
    address: 'Shop 4, C-Block Commercial Complex, Hauz Khas',
    distanceKm: 1.4,
    rating: 4.6,
    isOpen24x7: false,
    phone: '+91 11 2686 4411',
    estimatedDeliveryMins: 35,
    deliveryFee: 29,
    operatingHours: '08:00 AM - 11:00 PM',
    deliveryRadiusKm: 6.0,
    licenseNumber: 'DL-2025-PHA-41029'
  },
  {
    id: 'pharma-3',
    name: 'Tata 1mg Neighborhood Chemist',
    address: 'SCF 18, Sector 14 Urban Estate',
    distanceKm: 2.1,
    rating: 4.7,
    isOpen24x7: true,
    phone: '+91 11 2625 9900',
    estimatedDeliveryMins: 30,
    deliveryFee: 0
  }
];

export const initialPharmacyOrders: PharmacyOrder[] = [
  {
    id: 'ord-101',
    orderNumber: 'QA-ORD-9021',
    patientProfileId: 'usr-101',
    patientName: 'Arjun Sharma',
    pharmacyId: 'pharma-1',
    pharmacyName: 'Apollo 24|7 Express Pharmacy',
    items: [
      {
        medicineId: 'med-3',
        medicineName: 'Montair LC (10mg / 5mg)',
        genericName: 'Montelukast Sodium + Levocetirizine',
        strength: '10mg / 5mg',
        form: 'tablet',
        quantity: 2,
        unitPrice: 204,
        mrp: 255,
        totalPrice: 408,
        requiresPrescription: true
      },
      {
        medicineId: 'med-1',
        medicineName: 'Cetaphil Gentle Skin Cleanser (125ml)',
        genericName: 'Hydrating Face Wash',
        strength: '125ml',
        form: 'cleanser',
        quantity: 1,
        unitPrice: 341,
        mrp: 428,
        totalPrice: 341,
        requiresPrescription: false
      }
    ],
    subtotal: 749,
    discountAmount: 134,
    deliveryFee: 0,
    totalAmount: 749,
    deliveryType: 'delivery',
    deliveryAddress: 'Flat 402, Heritage Heights, Green Park, New Delhi',
    status: 'out_for_delivery',
    requiresPrescription: true,
    prescriptionDocumentId: 'doc-1',
    prescriptionFileName: 'Prescription_Dr_Ananya_Aug2026.pdf',
    prescriptionVerified: true,
    estimatedDeliveryTime: 'Arriving in ~15 mins',
    createdAt: '2026-08-27T03:30:00.000Z',
    paymentMethod: 'upi',
    paymentStatus: 'paid'
  }
];

export const initialMedicationSchedules: MedicationSchedule[] = [
  {
    id: 'sched-1',
    patientProfileId: 'usr-101',
    patientName: 'Arjun Sharma',
    medicineName: 'Montair LC',
    genericName: 'Montelukast Sodium (10mg) + Levocetirizine (5mg)',
    strength: '10mg / 5mg',
    form: 'tablet',
    unit: 'tablets',
    dosage: '1 Tablet',
    doseQuantity: 1,
    frequency: 'Once Daily (Night)',
    timing: 'bedtime',
    timesOfDay: ['21:30'],
    startDate: '2026-08-01',
    isChronic: false,
    endDate: '2026-09-15',
    initialQuantity: 30,
    remainingQuantity: 8,
    refillThreshold: 5,
    instructions: 'Take with warm water before sleeping. Do not drive immediately after.',
    colorTag: '#0d9488',
    isActive: true,
    status: 'active',
    prescribingDoctor: 'Dr. Ananya Roy (Pulmonologist)',
    prescriptionReference: 'Rx #QA-2026-901',
    notes: 'Seasonal allergic rhinitis management.',
    reminderEnabled: true,
  },
  {
    id: 'sched-2',
    patientProfileId: 'fam-1',
    patientName: 'Savitri Sharma (Mother)',
    medicineName: 'Telma 40',
    genericName: 'Telmisartan Tablets IP',
    strength: '40mg',
    form: 'tablet',
    unit: 'tablets',
    dosage: '1 Tablet',
    doseQuantity: 1,
    frequency: 'Once Daily (Morning)',
    timing: 'after_food',
    timesOfDay: ['08:30'],
    startDate: '2025-01-01',
    isChronic: true,
    initialQuantity: 60,
    remainingQuantity: 4,
    refillThreshold: 7,
    instructions: 'Check Blood Pressure weekly. Keep recorded in the log.',
    colorTag: '#0284c7',
    isActive: true,
    status: 'refill_required',
    prescribingDoctor: 'Dr. Rajesh Kumar (Cardiologist)',
    prescriptionReference: 'Rx #MED-2025-442',
    notes: 'Primary hypertension management.',
    reminderEnabled: true,
  },
  {
    id: 'sched-3',
    patientProfileId: 'fam-2',
    patientName: 'Ramesh Sharma (Father)',
    medicineName: 'Glycomet-GP 1',
    genericName: 'Metformin Hydrochloride (500mg) + Glimepiride (1mg)',
    strength: '500mg / 1mg',
    form: 'tablet',
    unit: 'tablets',
    dosage: '1 Tablet',
    doseQuantity: 1,
    frequency: 'Twice Daily (Morning, Night)',
    timing: 'before_food',
    timesOfDay: ['08:00', '20:00'],
    startDate: '2024-06-01',
    isChronic: true,
    initialQuantity: 60,
    remainingQuantity: 18,
    refillThreshold: 10,
    instructions: 'Take 15 minutes before breakfast and dinner. Do not skip meals.',
    colorTag: '#d97706',
    isActive: true,
    status: 'active',
    prescribingDoctor: 'Dr. Sunita Rao (Endocrinologist)',
    prescriptionReference: 'Rx #DIA-2024-108',
    notes: 'Type 2 Diabetes Mellitus glycemic control.',
    reminderEnabled: true,
  },
  {
    id: 'sched-4',
    patientProfileId: 'fam-1',
    patientName: 'Savitri Sharma (Mother)',
    medicineName: 'Shelcal 500',
    genericName: 'Calcium Carbonate (1250mg eq to Calcium 500mg) + Vitamin D3 (250 IU)',
    strength: '500mg',
    form: 'tablet',
    unit: 'tablets',
    dosage: '1 Tablet',
    doseQuantity: 1,
    frequency: 'Once Daily (Afternoon)',
    timing: 'after_food',
    timesOfDay: ['13:30'],
    startDate: '2025-03-15',
    isChronic: true,
    initialQuantity: 30,
    remainingQuantity: 12,
    refillThreshold: 5,
    instructions: 'Take after lunch with a glass of water.',
    colorTag: '#16a34a',
    isActive: true,
    status: 'active',
    prescribingDoctor: 'Dr. Rajesh Kumar (Cardiologist)',
    prescriptionReference: 'Rx #MED-2025-442',
    notes: 'Bone density support.',
    reminderEnabled: true,
  }
];

export const initialMedicationLogs: MedicationLog[] = [
  {
    id: 'log-1',
    scheduleId: 'sched-2',
    medicineName: 'Telma 40',
    scheduledTime: 'Today, 08:30 AM',
    takenTime: '08:32 AM',
    status: 'taken'
  },
  {
    id: 'log-2',
    scheduleId: 'sched-3',
    medicineName: 'Glycomet-GP 1',
    scheduledTime: 'Today, 08:00 AM',
    takenTime: '08:05 AM',
    status: 'taken'
  },
  {
    id: 'log-3',
    scheduleId: 'sched-4',
    medicineName: 'Shelcal 500',
    scheduledTime: 'Today, 01:30 PM',
    status: 'pending'
  },
  {
    id: 'log-4',
    scheduleId: 'sched-1',
    medicineName: 'Montair LC',
    scheduledTime: 'Today, 09:30 PM',
    status: 'pending'
  },
  {
    id: 'log-5',
    scheduleId: 'sched-3',
    medicineName: 'Glycomet-GP 1',
    scheduledTime: 'Today, 08:00 PM',
    status: 'pending'
  }
];

export const initialAppointments: Appointment[] = [
  {
    id: 'apt-1',
    appointmentNumber: 'QA-APT-2026-901',
    doctorId: 'doc-1',
    doctorName: 'Dr. Ananya Roy',
    doctorSpecialty: 'Cardiologist',
    doctorAvatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=200&auto=format&fit=crop&q=80',
    patientProfileId: 'fam-1',
    patientName: 'Savitri Sharma (Mother)',
    hospitalName: 'Apollo Heart Institute',
    dateTime: 'Tomorrow at 11:00 AM',
    type: 'in_person',
    status: 'confirmed',
    tokenNumber: 8,
    currentQueueToken: 4,
    symptoms: 'Routine 6-month hypertensive cardiac checkup and 2D-Echocardiogram review.',
    consultationFee: 1200,
    paymentStatus: 'paid'
  },
  {
    id: 'apt-2',
    appointmentNumber: 'QA-APT-2026-882',
    doctorId: 'doc-2',
    doctorName: 'Dr. Rajesh Deshmukh',
    doctorSpecialty: 'Endocrinologist',
    doctorAvatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=200&auto=format&fit=crop&q=80',
    patientProfileId: 'fam-2',
    patientName: 'Ramesh Sharma (Father)',
    hospitalName: 'Fortis Health Center',
    dateTime: 'Saturday, 30 Aug at 03:00 PM',
    type: 'video_teleconsult',
    status: 'booked',
    symptoms: 'Quarterly HbA1c titration and fasting glucose management.',
    meetingLink: 'https://telehealth.quickaarogya.in/room/dr-rajesh-deshmukh-882',
    consultationFee: 1000,
    paymentStatus: 'paid'
  }
];

export const initialMedicalDocuments: MedicalDocument[] = [
  {
    id: 'doc-rec-1',
    patientProfileId: 'usr-101',
    patientName: 'Arjun Sharma',
    category: 'prescription',
    title: 'Allergy & Bronchial Care Prescription',
    doctorOrLabName: 'Dr. Vivek Mehra, MBBS',
    date: '2026-08-01',
    fileUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
    fileSizeBytes: 1420000,
    tags: ['Prescription', 'Asthma', 'Montair LC', 'Cipla'],
    isAiExtracted: true,
    extractedSummary: 'Rx: Montair LC 1 tab OD at night x 45 days. Steam inhalation twice daily. Avoid cold food items.'
  },
  {
    id: 'doc-rec-2',
    patientProfileId: 'fam-2',
    patientName: 'Ramesh Sharma (Father)',
    category: 'lab_report',
    title: 'Comprehensive Diabetic & Lipid Profile',
    doctorOrLabName: 'Dr. Lal PathLabs',
    date: '2026-07-28',
    fileUrl: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=800&auto=format&fit=crop&q=80',
    fileSizeBytes: 2150000,
    tags: ['HbA1c', 'Lipid Profile', 'Creatinine', 'Fasting Blood Sugar'],
    isAiExtracted: true,
    extractedSummary: 'HbA1c measured at 6.8% (Good diabetic control). Total Cholesterol slightly elevated at 214 mg/dL. Renal function normal.'
  },
  {
    id: 'doc-rec-3',
    patientProfileId: 'fam-1',
    patientName: 'Savitri Sharma (Mother)',
    category: 'radiology_scan',
    title: 'Digital X-Ray Bilateral Knees (AP/Lat)',
    doctorOrLabName: 'Mahajan Imaging Center',
    date: '2026-05-14',
    fileUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&auto=format&fit=crop&q=80',
    fileSizeBytes: 4800000,
    tags: ['X-Ray', 'Knee', 'Osteoarthritis', 'Grade 2'],
    isAiExtracted: true,
    extractedSummary: 'Grade II medial joint space narrowing in both knees. Mild subchondral sclerosis. Recommended physiotherapeutic quad exercises.'
  }
];

export const initialBiomarkers: BiomarkerReportItem[] = [
  {
    id: 'bio-1',
    documentId: 'doc-rec-2',
    biomarker: 'HbA1c (Glycated Hemoglobin)',
    value: '6.8',
    numericValue: 6.8,
    unit: '%',
    refMin: 4.0,
    refMax: 5.6,
    status: 'high',
    explanation: 'Indicates good average blood sugar control over the past 3 months for a diabetic patient.'
  },
  {
    id: 'bio-2',
    documentId: 'doc-rec-2',
    biomarker: 'Fasting Blood Sugar (FBS)',
    value: '112',
    numericValue: 112,
    unit: 'mg/dL',
    refMin: 70,
    refMax: 99,
    status: 'high',
    explanation: 'Slightly above normal fasting threshold; maintain current low-glycemic dietary regimen.'
  },
  {
    id: 'bio-3',
    documentId: 'doc-rec-2',
    biomarker: 'Serum Creatinine',
    value: '0.92',
    numericValue: 0.92,
    unit: 'mg/dL',
    refMin: 0.7,
    refMax: 1.3,
    status: 'normal',
    explanation: 'Kidney filtration efficiency is healthy and within optimal range.'
  },
  {
    id: 'bio-4',
    documentId: 'doc-rec-2',
    biomarker: 'Total Cholesterol',
    value: '214',
    numericValue: 214,
    unit: 'mg/dL',
    refMin: 125,
    refMax: 200,
    status: 'high',
    explanation: 'Mild elevation. Recommended brisk walking 30 mins daily and reducing saturated fats.'
  }
];

export const initialLabTests: LabTest[] = [
  {
    id: 'lab-1',
    name: 'Comprehensive Health & Full Body Checkup (72 Tests)',
    category: 'Health Checkup Package',
    sampleType: 'Blood & Urine',
    fastingRequiredHours: 10,
    reportTurnaroundHours: 24,
    price: 1499,
    mrp: 3200,
    description: 'Includes Complete Hemogram, Lipid Profile, Liver Function (LFT), Kidney Function (KFT), Thyroid (TSH), Blood Sugar, and Urine Routine.',
    parametersCount: 72
  },
  {
    id: 'lab-2',
    name: 'HbA1c & Average Blood Glucose Panel',
    category: 'Blood Test',
    sampleType: 'Blood',
    fastingRequiredHours: 0,
    reportTurnaroundHours: 12,
    price: 399,
    mrp: 650,
    description: 'Gold standard test for 3-month glycemic history. No fasting required.',
    parametersCount: 3
  },
  {
    id: 'lab-3',
    name: 'Vitamin D (25-OH) & Vitamin B12 Vitality Duo',
    category: 'Blood Test',
    sampleType: 'Blood',
    fastingRequiredHours: 0,
    reportTurnaroundHours: 18,
    price: 899,
    mrp: 1800,
    description: 'Crucial for bone density, nerve vitality, fatigue diagnosis, and immunity evaluation.',
    parametersCount: 2
  },
  {
    id: 'lab-4',
    name: 'Complete Lipid & Cardiovascular Risk Profile',
    category: 'Blood Test',
    sampleType: 'Blood',
    fastingRequiredHours: 12,
    reportTurnaroundHours: 12,
    price: 450,
    mrp: 850,
    description: 'Measures Total Cholesterol, HDL Good Cholesterol, LDL Bad Cholesterol, Triglycerides, and VLDL.',
    parametersCount: 8
  }
];

export const initialLabBookings: LabBooking[] = [
  {
    id: 'lb-101',
    bookingNumber: 'QA-LAB-2026-441',
    patientProfileId: 'fam-2',
    patientName: 'Ramesh Sharma (Father)',
    testNames: ['Comprehensive Health & Full Body Checkup (72 Tests)'],
    totalPrice: 1499,
    collectionType: 'home_collection',
    scheduledDate: '2026-08-29',
    scheduledTimeSlot: '07:30 AM - 08:30 AM',
    status: 'collector_assigned',
    phlebotomistName: 'Sunil Kumar (Certified Phlebotomist)',
    phlebotomistPhone: '+91 98711 55667'
  }
];

export const initialHealthcareExpenses: HealthcareExpense[] = [
  {
    id: 'exp-1',
    patientProfileId: 'usr-101',
    title: 'Monthly Chronic Medicines (Telma + Glycomet + Shelcal)',
    category: 'medicines',
    amount: 1420,
    date: '2026-08-15',
    paymentMethod: 'UPI',
    isInsuranceClaimed: false
  },
  {
    id: 'exp-2',
    patientProfileId: 'fam-1',
    title: 'Dr. Ananya Roy Cardiology Consultation',
    category: 'doctor_consultation',
    amount: 1200,
    date: '2026-08-10',
    paymentMethod: 'Credit Card',
    isInsuranceClaimed: true,
    claimStatus: 'settled'
  },
  {
    id: 'exp-3',
    patientProfileId: 'fam-2',
    title: 'Quarterly Full Body Preventive Lab Test',
    category: 'lab_diagnostics',
    amount: 1499,
    date: '2026-07-28',
    paymentMethod: 'UPI',
    isInsuranceClaimed: false
  }
];

export const initialInboxItems: HealthInboxItem[] = [
  {
    id: 'inbox-1',
    userId: 'usr-101',
    category: 'appointments',
    type: 'appointment',
    title: 'Appointment Tomorrow with Dr. Ananya Roy',
    message: 'Follow-up consultation scheduled for tomorrow at 11:00 AM at Apollo Hospital. Token queue allocated: #8.',
    priority: 'important',
    isRead: false,
    timestamp: '20 mins ago',
    createdAt: '2026-08-27T05:00:00Z',
    relatedEntity: {
      type: 'appointment',
      id: 'apt-1',
      name: 'Dr. Ananya Roy (Cardiologist)'
    },
    action: {
      label: 'View Appointment',
      url: '/appointments'
    },
    deliveryChannels: [
      { channel: 'in_app', status: 'delivered', sentAt: '2026-08-27T05:00:00Z' },
      { channel: 'push', status: 'delivered', provider: 'FCM Gateway', sentAt: '2026-08-27T05:00:01Z' },
      { channel: 'sms', status: 'delivered', provider: 'Twilio SMS', sentAt: '2026-08-27T05:00:02Z' },
      { channel: 'whatsapp', status: 'delivered', provider: 'Meta Cloud API', sentAt: '2026-08-27T05:00:02Z' }
    ],
    familyMemberId: 'fam-1',
    familyMemberName: 'Savitri Sharma (Mother)'
  },
  {
    id: 'inbox-2',
    userId: 'usr-101',
    category: 'medicines',
    type: 'refill_alert',
    title: 'Medicine Running Low: Telma 40',
    message: 'Only 4 tablets remaining for Savitri Sharma. At 1 tablet daily, medication will run out in ~4 days.',
    priority: 'important',
    isRead: false,
    timestamp: '45 mins ago',
    createdAt: '2026-08-27T04:30:00Z',
    relatedEntity: {
      type: 'medication',
      id: 'sched-2',
      name: 'Telma 40 (Telmisartan 40mg)'
    },
    action: {
      label: '1-Click Refill',
      url: '/medicines'
    },
    deliveryChannels: [
      { channel: 'in_app', status: 'delivered', sentAt: '2026-08-27T04:30:00Z' },
      { channel: 'push', status: 'delivered', provider: 'FCM Gateway', sentAt: '2026-08-27T04:30:01Z' }
    ],
    familyMemberId: 'fam-1',
    familyMemberName: 'Savitri Sharma (Mother)'
  },
  {
    id: 'inbox-3',
    userId: 'usr-101',
    category: 'family',
    type: 'family_attention',
    title: 'Family Member Needs Attention: High Blood Pressure Alert',
    message: 'Savitri Sharma reported elevated blood pressure reading (148/92 mmHg). Review care plan and medication adherence.',
    priority: 'urgent',
    isRead: false,
    timestamp: '1 hour ago',
    createdAt: '2026-08-27T04:15:00Z',
    relatedEntity: {
      type: 'family_member',
      id: 'fam-1',
      name: 'Savitri Sharma'
    },
    action: {
      label: 'View Care Circle',
      url: '/family'
    },
    deliveryChannels: [
      { channel: 'in_app', status: 'delivered', sentAt: '2026-08-27T04:15:00Z' },
      { channel: 'push', status: 'delivered', provider: 'FCM High Priority', sentAt: '2026-08-27T04:15:01Z' },
      { channel: 'sms', status: 'delivered', provider: 'Twilio SMS', sentAt: '2026-08-27T04:15:02Z' }
    ],
    familyMemberId: 'fam-1',
    familyMemberName: 'Savitri Sharma'
  },
  {
    id: 'inbox-4',
    userId: 'usr-101',
    category: 'medicines',
    type: 'dose_reminder',
    title: 'Medicine Due: Glycomet-GP 1',
    message: 'Morning dose (1 Tablet before breakfast) scheduled at 08:00 AM for Ramesh Sharma.',
    priority: 'important',
    isRead: false,
    timestamp: '2 hours ago',
    createdAt: '2026-08-27T03:30:00Z',
    relatedEntity: {
      type: 'medication',
      id: 'sched-3',
      name: 'Glycomet-GP 1'
    },
    action: {
      label: 'Log Dose',
      url: '/medicines'
    },
    deliveryChannels: [
      { channel: 'in_app', status: 'delivered', sentAt: '2026-08-27T03:30:00Z' },
      { channel: 'push', status: 'delivered', provider: 'FCM Gateway', sentAt: '2026-08-27T03:30:01Z' }
    ],
    familyMemberId: 'fam-2',
    familyMemberName: 'Ramesh Sharma (Father)'
  },
  {
    id: 'inbox-5',
    userId: 'usr-101',
    category: 'appointments',
    type: 'appointment_cancelled',
    title: 'Appointment Cancelled: Dr. Siddharth Verma',
    message: 'Orthopedic consultation on 2026-09-06 was cancelled. Fee refund of ₹1,100 has been initiated to your UPI account.',
    priority: 'urgent',
    isRead: false,
    timestamp: '3 hours ago',
    createdAt: '2026-08-27T02:00:00Z',
    relatedEntity: {
      type: 'appointment',
      id: 'apt-cancelled-1',
      name: 'Dr. Siddharth Verma'
    },
    action: {
      label: 'Reschedule Visit',
      url: '/appointments'
    },
    deliveryChannels: [
      { channel: 'in_app', status: 'delivered', sentAt: '2026-08-27T02:00:00Z' },
      { channel: 'sms', status: 'delivered', provider: 'Twilio SMS', sentAt: '2026-08-27T02:00:01Z' },
      { channel: 'email', status: 'delivered', provider: 'Resend Mail', sentAt: '2026-08-27T02:00:02Z' }
    ]
  },
  {
    id: 'inbox-6',
    userId: 'usr-101',
    category: 'tests',
    type: 'lab_ready',
    title: 'Lab Report Available: Comprehensive Diabetic & Lipid Profile',
    message: 'Diagnostic test results from Dr. Lal PathLabs are verified and ready for download in your Medical Vault.',
    priority: 'normal',
    isRead: true,
    timestamp: 'Yesterday',
    createdAt: '2026-08-26T14:00:00Z',
    relatedEntity: {
      type: 'lab_booking',
      id: 'lb-101',
      name: 'Comprehensive Diabetic & Lipid Profile'
    },
    action: {
      label: 'View Lab Report',
      url: '/records'
    },
    deliveryChannels: [
      { channel: 'in_app', status: 'delivered', sentAt: '2026-08-26T14:00:00Z' },
      { channel: 'whatsapp', status: 'delivered', provider: 'Meta Cloud API', sentAt: '2026-08-26T14:00:01Z' }
    ],
    familyMemberId: 'fam-2',
    familyMemberName: 'Ramesh Sharma'
  },
  {
    id: 'inbox-7',
    userId: 'usr-101',
    category: 'records',
    type: 'prescription_uploaded',
    title: 'Prescription Uploaded: Allergy & Bronchial Care',
    message: 'Dr. Vivek Mehra added an encrypted digital prescription (Rx #QA-2026-901) for Montair LC 10mg.',
    priority: 'normal',
    isRead: true,
    timestamp: '2 days ago',
    createdAt: '2026-08-25T11:00:00Z',
    relatedEntity: {
      type: 'document',
      id: 'doc-rec-1',
      name: 'Allergy & Bronchial Care Prescription'
    },
    action: {
      label: 'Open Document Vault',
      url: '/records'
    },
    deliveryChannels: [
      { channel: 'in_app', status: 'delivered', sentAt: '2026-08-25T11:00:00Z' },
      { channel: 'email', status: 'delivered', provider: 'Resend Mail', sentAt: '2026-08-25T11:00:02Z' }
    ]
  },
  {
    id: 'inbox-8',
    userId: 'usr-101',
    category: 'appointments',
    type: 'followup_due',
    title: 'Follow-Up Due: Quarterly HbA1c Review',
    message: '3 months since last endocrinology consultation with Dr. Rajesh Deshmukh. Schedule your routine glycemic review.',
    priority: 'important',
    isRead: false,
    timestamp: '3 days ago',
    createdAt: '2026-08-24T09:00:00Z',
    relatedEntity: {
      type: 'appointment',
      id: 'apt-2',
      name: 'Dr. Rajesh Deshmukh'
    },
    action: {
      label: 'Book Consultation',
      url: '/doctors'
    },
    deliveryChannels: [
      { channel: 'in_app', status: 'delivered', sentAt: '2026-08-24T09:00:00Z' },
      { channel: 'push', status: 'delivered', provider: 'FCM Gateway', sentAt: '2026-08-24T09:00:01Z' }
    ],
    familyMemberId: 'fam-2',
    familyMemberName: 'Ramesh Sharma'
  },
  {
    id: 'inbox-9',
    userId: 'usr-101',
    category: 'orders',
    type: 'order_delivered',
    title: 'Medicine Order Delivered: Apollo 24|7 Express',
    message: 'Order #QA-ORD-9021 containing Montair LC and Cetaphil Gentle Cleanser was delivered to Flat 402, Heritage Heights.',
    priority: 'normal',
    isRead: true,
    timestamp: '4 days ago',
    createdAt: '2026-08-23T16:20:00Z',
    relatedEntity: {
      type: 'order',
      id: 'ord-101',
      name: 'Order #QA-ORD-9021'
    },
    action: {
      label: 'View Order Details',
      url: '/pharmacies'
    },
    deliveryChannels: [
      { channel: 'in_app', status: 'delivered', sentAt: '2026-08-23T16:20:00Z' },
      { channel: 'sms', status: 'delivered', provider: 'Twilio SMS', sentAt: '2026-08-23T16:20:01Z' }
    ]
  },
  {
    id: 'inbox-10',
    userId: 'usr-101',
    category: 'payments',
    type: 'payment_completed',
    title: 'Payment Completed: ₹1,200 via UPI',
    message: 'Consultation fee for Dr. Ananya Roy confirmed. Official Section 80D tax invoice is available.',
    priority: 'normal',
    isRead: true,
    timestamp: '5 days ago',
    createdAt: '2026-08-22T10:15:00Z',
    relatedEntity: {
      type: 'payment',
      id: 'pay-101',
      name: 'UPI Ref: 681920381029'
    },
    action: {
      label: 'Download Invoice',
      url: '/expenses'
    },
    deliveryChannels: [
      { channel: 'in_app', status: 'delivered', sentAt: '2026-08-22T10:15:00Z' },
      { channel: 'email', status: 'delivered', provider: 'Resend Mail', sentAt: '2026-08-22T10:15:02Z' }
    ]
  }
];

export const initialNotifications: HealthNotification[] = initialInboxItems.map(item => ({
  id: item.id,
  type: item.type,
  title: item.title,
  message: item.message,
  time: item.timestamp,
  isRead: item.isRead,
  actionUrl: item.action?.url,
  urgency: item.priority === 'urgent' ? 'high' : item.priority === 'important' ? 'medium' : 'low',
  category: item.category,
  priority: item.priority,
  relatedEntity: item.relatedEntity,
  actionLabel: item.action?.label
}));

